sudo: false
language: ruby
rvm:
- 2.2.4
before_install:
- rvm use @global
- gem uninstall bundler -x || gem uninstall bundler -a || true
- gem install bundler -v 1.17.3
- bundler --version
script:
- rvm use @global
- bundle exec rake
jobs:
  include:
  - stage: gem release
    rvm: 2.2.4
    script: echo "Deploying to rubygems.org ..."
    deploy:
      provider: rubygems
      api_key:
        secure: NEA7BYENheSN8qF/6BP52uQjTS5U43MXsyxBeqxbp1JOkJxVSNzQw14xy41aXX0gphT7wEVHinnWS+1slLKXvu4OzGKKzcUsnekYFZoGW7eTyKUx7lh/XtFejQ/Mm4P5t75GBgMoaIi+Pa1rD4fcE7zYGrgCvTwIrOGb/SPIKILj0yT8UXMFod8yDDmxzivSSKYe4rgWYlq8aiidDZr2M5ypBR4WcOptCrkBCF8XxXzhFMY4QtrXLsLFRyCzCrDHmosCfC/bLJQltlJjLXfB5ksgaImWAD7wZ6Q4uC5QqmPShonQiPlLEh53Q5nkEWPIcsV7FVZqzXUjPN3LYHlRv+7D3AvbHmJggSt7fXr8YxbzVUkviBlKqNmc9cqM6CSO++QT3UShNgH5b03YKI8rRjFMWYKn1DrN5F5rFNDoGFcZtQSjFN5g/fEiSYsdkNsIeTp4YFxMkTztAYT8TxgcBvCnfXox6xDaLaPWh13UrUL2VL7O7uDK06xWUCp9Hm3/AXz0wRzya1tK9dCWamE5BOzk2ScOiLOgmpgwNHFVA1U93rkHq7Ixr11wazP3Dcinv0kWcW7hdMcI7VA0DUesxLKw6mkcQpd3NLgSU4mWtpoVFcmdERQUGsNM1d5NjGjBeyVMpC0I9NXM1Wv6cLENSX9b4GR7lkwGG/IHRFNciHk=
      gem: pact-message
      on:
        tags: true
        repo: pact-foundation/pact-message-ruby
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/6523128341fad111ed79
    on_success: change
    on_failure: always
    on_start: never

